package com.csti.ce.seguridad.domain;
// Generated 26/04/2014 10:50:12 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Modulo generated by hbm2java
 */
public class Modulo  implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;


     private int idModulo;
     private String codigo;
     private String nombre;
     private String descripcion;
     private String icono;
     private Character activo;
     private Integer orden;
     private Set opcions = new HashSet(0);
     private Sistema sistema ;

    public Sistema getSistema() {
        return sistema;
    }

    public void setSistema(Sistema sistema) {
        this.sistema = sistema;
    }

    public Modulo() {
    }

	
    public Modulo(int idModulo) {
        this.idModulo = idModulo;
    }
    public Modulo(int idModulo, String codigo, String nombre, String descripcion, String icono, Character activo, Integer orden, Set opcions, Sistema sistema) {
       this.idModulo = idModulo;
       this.codigo = codigo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.icono = icono;
       this.activo = activo;
       this.orden = orden;
       this.opcions = opcions;
       this.sistema = sistema;
    }
   
    public int getIdModulo() {
        return this.idModulo;
    }
    
    public void setIdModulo(int idModulo) {
        this.idModulo = idModulo;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getIcono() {
        return this.icono;
    }
    
    public void setIcono(String icono) {
        this.icono = icono;
    }
    public Character getActivo() {
        return this.activo;
    }
    
    public void setActivo(Character activo) {
        this.activo = activo;
    }
    public Integer getOrden() {
        return this.orden;
    }
    
    public void setOrden(Integer orden) {
        this.orden = orden;
    }
    public Set getOpcions() {
        return this.opcions;
    }
    
    public void setOpcions(Set opcions) {
        this.opcions = opcions;
    }




}


