package com.csti.ce.seguridad.domain;
// Generated 26/04/2014 10:50:12 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Opcion generated by hbm2java
 */
public class Opcion implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

    private int idOpcion;
    private Modulo modulo;
    private String codigo;
    private String nombre;
    private String descripcion;
    private String orden;
    private String icono;
    private String controlador;
    private Character esDirectorio;
    private String vista;
    private Character activo;
    private Set accesos = new HashSet(0);

    public Opcion() {
    }

    public Opcion(int id) {
        this.idOpcion = id;
    }

    public Opcion(int idOpcion, Modulo modulo) {
        this.idOpcion = idOpcion;
        this.modulo = modulo;
    }

    public Opcion(int idOpcion, Modulo modulo, String codigo, String nombre, String descripcion, String orden, String icono, String controlador, Character esDirectorio, String vista, Character activo, Set accesos) {
        this.idOpcion = idOpcion;
        this.modulo = modulo;
        this.codigo = codigo;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.orden = orden;
        this.icono = icono;
        this.controlador = controlador;
        this.esDirectorio = esDirectorio;
        this.vista = vista;
        this.activo = activo;
        this.accesos = accesos;
    }

    public int getIdOpcion() {
        return this.idOpcion;
    }

    public void setIdOpcion(int idOpcion) {
        this.idOpcion = idOpcion;
    }

    public Modulo getModulo() {
        return this.modulo;
    }

    public void setModulo(Modulo modulo) {
        this.modulo = modulo;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getOrden() {
        return this.orden;
    }

    public void setOrden(String orden) {
        this.orden = orden;
    }

    public String getIcono() {
        return this.icono;
    }

    public void setIcono(String icono) {
        this.icono = icono;
    }

    public String getControlador() {
        return this.controlador;
    }

    public void setControlador(String controlador) {
        this.controlador = controlador;
    }

    public Character getEsDirectorio() {
        return this.esDirectorio;
    }

    public void setEsDirectorio(Character esDirectorio) {
        this.esDirectorio = esDirectorio;
    }

    public String getVista() {
        return this.vista;
    }

    public void setVista(String vista) {
        this.vista = vista;
    }

    public Character getActivo() {
        return this.activo;
    }

    public void setActivo(Character activo) {
        this.activo = activo;
    }

    public Set getAccesos() {
        return this.accesos;
    }

    public void setAccesos(Set accesos) {
        this.accesos = accesos;
    }

}
