package com.csti.ce.seguridad.domain;
// Generated 26/04/2014 10:50:12 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Permiso generated by hbm2java
 */
public class Permiso implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idPermiso;
    private String codigo;
    private String nombre;
    private String descripcion;
    private Character activo;
    private char actualizar;
    private char eliminar;
    private char agregar;
    private char lectura;
    private char todo;
    private Set accesos = new HashSet(0);

    public Permiso() {
    }
    
    public Permiso(int id){
        this.idPermiso = id;
    }

    public Permiso(int idPermiso, char actualizar, char eliminar, char agregar, char lectura) {
        this.idPermiso = idPermiso;
        this.actualizar = actualizar;
        this.eliminar = eliminar;
        this.agregar = agregar;
        this.lectura = lectura;
    }

    public Permiso(int idPermiso, String codigo, String nombre, String descripcion, Character activo, char actualizar, char eliminar, char agregar, char lectura, Set accesos) {
        this.idPermiso = idPermiso;
        this.codigo = codigo;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.activo = activo;
        this.actualizar = actualizar;
        this.eliminar = eliminar;
        this.agregar = agregar;
        this.lectura = lectura;
        this.accesos = accesos;
    }

    public int getIdPermiso() {
        return this.idPermiso;
    }

    public void setIdPermiso(int idPermiso) {
        this.idPermiso = idPermiso;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Character getActivo() {
        return this.activo;
    }

    public void setActivo(Character activo) {
        this.activo = activo;
    }

    public char getActualizar() {
        return this.actualizar;
    }

    public void setActualizar(char actualizar) {
        this.actualizar = actualizar;
    }

    public char getEliminar() {
        return this.eliminar;
    }

    public void setEliminar(char eliminar) {
        this.eliminar = eliminar;
    }

    public char getAgregar() {
        return this.agregar;
    }

    public void setAgregar(char agregar) {
        this.agregar = agregar;
    }

    public char getLectura() {
        return this.lectura;
    }

    public void setLectura(char lectura) {
        this.lectura = lectura;
    }

    public Set getAccesos() {
        return this.accesos;
    }

    public void setAccesos(Set accesos) {
        this.accesos = accesos;
    }

    public Character getTodo() {
        return this.todo = (actualizar == '1' ? (eliminar == '1' ? (agregar == '1' ? (lectura == '1' ? '1'
                : '0')
                : '0')
                : '0')
                : '0');
    }

    public void setTodo(Character todo) {
        this.actualizar = todo;
        this.agregar = todo;
        this.eliminar = todo;
        this.lectura = todo;
        this.todo = todo;
    }

}
