package com.csti.ce.seguridad.domain;
// Generated 26/04/2014 10:50:12 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
     private int idPersona;
     private String tipoDocumento;
     private String razonSocial;
     private String email;
     private char activo;
     private Character sexo;
     private String imagen;
     private String nroDocumento;
     private String direccion;
     private String telefono;
     private Set usuarios = new HashSet(0);

    public Persona() {
    }
    
    public Persona(int idPersona) {
        this.idPersona = idPersona;
    }

	
    public Persona(int idPersona, String tipoDocumento, String razonSocial, char activo, String nroDocumento) {
        this.idPersona = idPersona;
        this.tipoDocumento = tipoDocumento;
        this.razonSocial = razonSocial;
        this.activo = activo;
        this.nroDocumento = nroDocumento;
    }
    public Persona(int idPersona, String tipoDocumento, String razonSocial, String email, char activo, Character sexo, String imagen, String nroDocumento, String direccion, String telefono, Set usuarios) {
       this.idPersona = idPersona;
       this.tipoDocumento = tipoDocumento;
       this.razonSocial = razonSocial;
       this.email = email;
       this.activo = activo;
       this.sexo = sexo;
       this.imagen = imagen;
       this.nroDocumento = nroDocumento;
       this.direccion = direccion;
       this.telefono = telefono;
       this.usuarios = usuarios;
    }
   
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }
    public String getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public char getActivo() {
        return this.activo;
    }
    
    public void setActivo(char activo) {
        this.activo = activo;
    }
    public Character getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public String getNroDocumento() {
        return this.nroDocumento;
    }
    
    public void setNroDocumento(String nroDocumento) {
        this.nroDocumento = nroDocumento;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


