package com.csti.ce.seguridad.domain;
// Generated 26/04/2014 10:50:12 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;


     private int idRol;
     private String codigo;
     private String nombre;
     private String descripcion;
     private Character activo;
     private String observacion;
     private Set usuarioRols = new HashSet(0);
     private Set accesos = new HashSet(0);
     private Sistema sistema ;

    public Sistema getSistema() {
        return sistema;
    }

    public void setSistema(Sistema sistema) {
        this.sistema = sistema;
    }

    public Rol() {
    }

	
    public Rol(int idRol) {
        this.idRol = idRol;
    }
    public Rol(int idRol, String codigo, String nombre, String descripcion, Character activo, String observacion, Set usuarioRols, Set accesos, Sistema sistema) {
       this.idRol = idRol;
       this.codigo = codigo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.activo = activo;
       this.observacion = observacion;
       this.usuarioRols = usuarioRols;
       this.accesos = accesos;
       this.sistema = sistema;
    }
   
    public int getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(int idRol) {
        this.idRol = idRol;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Character getActivo() {
        return this.activo;
    }
    
    public void setActivo(Character activo) {
        this.activo = activo;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Set getUsuarioRols() {
        return this.usuarioRols;
    }
    
    public void setUsuarioRols(Set usuarioRols) {
        this.usuarioRols = usuarioRols;
    }
    public Set getAccesos() {
        return this.accesos;
    }
    
    public void setAccesos(Set accesos) {
        this.accesos = accesos;
    }
}


