package com.csti.ce.seguridad.domain;
// Generated 26/04/2014 10:50:12 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Sistema generated by hbm2java
 */
public class Sistema implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

    private int idSistema;
    private String identificador;
    private String descripcion;
    private String nombre;
    private String licencia;
    private String ambiente;
    private Set usuarioSistemas = new HashSet(0);

    public Sistema() {
    }

    public Sistema(int idSistema) {
        this.idSistema = idSistema;
    }

    public Sistema(int idSistema, String identificador, String descripcion, String nombre, String licencia, Set usuarioSistemas) {
        this.idSistema = idSistema;
        this.identificador = identificador;
        this.descripcion = descripcion;
        this.nombre = nombre;
        this.licencia = licencia;
        this.usuarioSistemas = usuarioSistemas;
    }

    public int getIdSistema() {
        return this.idSistema;
    }

    public void setIdSistema(int idSistema) {
        this.idSistema = idSistema;
    }

    public String getIdentificador() {
        return this.identificador;
    }

    public void setIdentificador(String identificador) {
        this.identificador = identificador;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getLicencia() {
        return this.licencia;
    }

    public void setLicencia(String licencia) {
        this.licencia = licencia;
    }

    public Set getUsuarioSistemas() {
        return this.usuarioSistemas;
    }

    public void setUsuarioSistemas(Set usuarioSistemas) {
        this.usuarioSistemas = usuarioSistemas;
    }

    public void setAmbiente(String ambiente) {
        this.ambiente = ambiente;
    }

    public String getAmbiente() {
        return ambiente;
    }

}
