package com.csti.ce.seguridad.domain;
// Generated 26/04/2014 10:50:12 AM by Hibernate Tools 3.6.0

/**
 * UsuarioRol generated by hbm2java
 */
public class UsuarioRol implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

    private int idUsuarioRol;
    private Rol rol;
    private Usuario usuario;

    public UsuarioRol() {
    }

    public UsuarioRol(int id) {
        this.idUsuarioRol = id;
    }

    public UsuarioRol(int idUsuarioRol, Rol rol, Usuario usuario) {
        this.idUsuarioRol = idUsuarioRol;
        this.rol = rol;
        this.usuario = usuario;
    }

    public int getIdUsuarioRol() {
        return this.idUsuarioRol;
    }

    public void setIdUsuarioRol(int idUsuarioRol) {
        this.idUsuarioRol = idUsuarioRol;
    }

    public Rol getRol() {
        return this.rol;
    }

    public void setRol(Rol rol) {
        this.rol = rol;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

}
