package com.csti.ce.seguridad.domain;
// Generated 26/04/2014 10:50:12 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

    private int idUsuario;
    private Persona persona;
    private String userName;
    private String userPassword;
    private String sociedad;
    private char activo;
    private Set usuarioRols = new HashSet(0);
    private Set usuarioSistemas = new HashSet(0);
    private Set usuarioSeries = new HashSet(0);

    public Usuario() {
    }

    public Usuario(int id) {
        this.idUsuario = id;
    }

    public Usuario(int idUsuario, Persona persona, char activo) {
        this.idUsuario = idUsuario;
        this.persona = persona;
        this.activo = activo;
    }

    public Usuario(int idUsuario, Persona persona, String userName, String userPassword, char activo, Set usuarioRols, Set usuarioSistemas) {
        this.idUsuario = idUsuario;
        this.persona = persona;
        this.userName = userName;
        this.userPassword = userPassword;
        this.activo = activo;
        this.usuarioRols = usuarioRols;
        this.usuarioSistemas = usuarioSistemas;
    }

    public int getIdUsuario() {
        return this.idUsuario;
    }

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    public Persona getPersona() {
        return this.persona;
    }

    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserPassword() {
        return this.userPassword;
    }

    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    public char getActivo() {
        return this.activo;
    }

    public void setActivo(char activo) {
        this.activo = activo;
    }

    public Set getUsuarioRols() {
        return this.usuarioRols;
    }

    public void setUsuarioRols(Set usuarioRols) {
        this.usuarioRols = usuarioRols;
    }

    public Set getUsuarioSistemas() {
        return this.usuarioSistemas;
    }

    public void setUsuarioSistemas(Set usuarioSistemas) {
        this.usuarioSistemas = usuarioSistemas;
    }

    public void setUsuarioSeries(Set usuarioSeries) {
        this.usuarioSeries = usuarioSeries;
    }

    public Set getUsuarioSeries() {
        return usuarioSeries;
    }

	public String getSociedad() {
		return sociedad;
	}

	public void setSociedad(String sociedad) {
		this.sociedad = sociedad;
	}

}
