package com.csti.ce.seguridad.domain;
// Generated 26/04/2014 10:50:12 AM by Hibernate Tools 3.6.0



/**
 * UsuarioSistema generated by hbm2java
 */
public class UsuarioSistema  implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;


     private int idUsuarioSistema;
     private Usuario usuario;
     private Sistema sistema;

    public UsuarioSistema() {
    }

	
    public UsuarioSistema(int idUsuarioSistema) {
        this.idUsuarioSistema = idUsuarioSistema;
    }
    public UsuarioSistema(int idUsuarioSistema, Usuario usuario, Sistema sistema) {
       this.idUsuarioSistema = idUsuarioSistema;
       this.usuario = usuario;
       this.sistema = sistema;
    }
   
    public int getIdUsuarioSistema() {
        return this.idUsuarioSistema;
    }
    
    public void setIdUsuarioSistema(int idUsuarioSistema) {
        this.idUsuarioSistema = idUsuarioSistema;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Sistema getSistema() {
        return this.sistema;
    }
    
    public void setSistema(Sistema sistema) {
        this.sistema = sistema;
    }




}


