package com.csti.ce.monitor.domain;
// Generated 13/04/2014 12:19:59 PM by Hibernate Tools 3.6.0

/**
 * Clave generated by hbm2java
 */
public class Clave implements java.io.Serializable {

    private long idClave;
    private String ruc;
    private Integer ambiente;
    private String aleatorio;
    private Integer usado;

    public Clave() {
    }

    public Clave(long idClave) {
        this.idClave = idClave;
    }

    public Clave(long idClave, String ruc, Integer ambiente, String aleatorio, Integer usado) {
        this.idClave = idClave;
        this.ruc = ruc;
        this.ambiente = ambiente;
        this.aleatorio = aleatorio;
        this.usado = usado;
    }

    public long getIdClave() {
        return this.idClave;
    }

    public void setIdClave(long idClave) {
        this.idClave = idClave;
    }

    public String getRuc() {
        return this.ruc;
    }

    public void setRuc(String ruc) {
        this.ruc = ruc;
    }

    public Integer getAmbiente() {
        return this.ambiente;
    }

    public void setAmbiente(Integer ambiente) {
        this.ambiente = ambiente;
    }

    public String getAleatorio() {
        return this.aleatorio;
    }

    public void setAleatorio(String aleatorio) {
        this.aleatorio = aleatorio;
    }

    public Integer getUsado() {
        return this.usado;
    }

    public void setUsado(Integer usado) {
        this.usado = usado;
    }
}
