package com.csti.ce.monitor.domain;
// Generated 13/04/2014 12:19:59 PM by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * Comprobante generated by hbm2java
 */
public class Comprobante implements java.io.Serializable {

    private long idComprobante;
    private String ruc;
    private String nroSri;
    private String docReferencia;
    private Date fechaEmision;
    private String tipoDoc;
    private String tipoDocReferencia;
    private int tipoEmision;
    private String claveAcceso;
    private String nroAutorizacion;
    private String fechaAutorizacion;
    private int contabilizado;
    private int anulado;
    private String xml;
    private String nombreDocumento;
    private String documentXML;
    private String pathXml;
    private String pathPdf;
    private int escenario;
    private String estado;
    private String log;
    private int pdf;
    private int email;
    private int notificacion;
    private int ultimo;
    private int recepcionado;
    private int autorizado;
    private String usuario;
    private String terminal;
    private String emailDestino;
    private Date fechaRegistro;
    private String mensaje;
    private int offline;
    private String interlocutor;
    private String razonSocial;
    private String docSustento;
    private String rucCliente;

    public Comprobante() {
    }

    /**
     * @return the idComprobante
     */
    public long getIdComprobante() {
        return idComprobante;
    }

    /**
     * @param idComprobante the idComprobante to set
     */
    public void setIdComprobante(long idComprobante) {
        this.idComprobante = idComprobante;
    }

    /**
     * @return the ruc
     */
    public String getRuc() {
        return ruc;
    }

    /**
     * @param ruc the ruc to set
     */
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }

    /**
     * @return the nroSri
     */
    public String getNroSri() {
        return nroSri;
    }

    /**
     * @param nroSri the nroSri to set
     */
    public void setNroSri(String nroSri) {
        this.nroSri = nroSri;
    }

    /**
     * @return the docReferencia
     */
    public String getDocReferencia() {
        return docReferencia;
    }

    /**
     * @param docReferencia the docReferencia to set
     */
    public void setDocReferencia(String docReferencia) {
        this.docReferencia = docReferencia;
    }

    /**
     * @return the fechaEmision
     */
    public Date getFechaEmision() {
        return fechaEmision;
    }

    /**
     * @param fechaEmision the fechaEmision to set
     */
    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }

    /**
     * @return the tipoDoc
     */
    public String getTipoDoc() {
        return tipoDoc;
    }

    /**
     * @param tipoDoc the tipoDoc to set
     */
    public void setTipoDoc(String tipoDoc) {
        this.tipoDoc = tipoDoc;
    }

    /**
     * @return the tipoDocReferencia
     */
    public String getTipoDocReferencia() {
        return tipoDocReferencia;
    }

    /**
     * @param tipoDocReferencia the tipoDocReferencia to set
     */
    public void setTipoDocReferencia(String tipoDocReferencia) {
        this.tipoDocReferencia = tipoDocReferencia;
    }

    /**
     *
     * @return the tipoEmision
     */
    public int getTipoEmision() {
        return tipoEmision;
    }

    /**
     *
     * @param tipoEmision the tipoEmision to set
     */
    public void setTipoEmision(int tipoEmision) {
        this.tipoEmision = tipoEmision;
    }

    /**
     * @return the claveAcceso
     */
    public String getClaveAcceso() {
        return claveAcceso;
    }

    /**
     * @param claveAcceso the claveAcceso to set
     */
    public void setClaveAcceso(String claveAcceso) {
        this.claveAcceso = claveAcceso;
    }

    /**
     * @return the nroAutorizacion
     */
    public String getNroAutorizacion() {
        return nroAutorizacion;
    }

    /**
     * @param nroAutorizacion the nroAutorizacion to set
     */
    public void setNroAutorizacion(String nroAutorizacion) {
        this.nroAutorizacion = nroAutorizacion;
    }

    /**
     * @return the fechaAutorizacion
     */
    public String getFechaAutorizacion() {
        return fechaAutorizacion;
    }

    /**
     * @param fechaAutorizacion the fechaAutorizacion to set
     */
    public void setFechaAutorizacion(String fechaAutorizacion) {
        this.fechaAutorizacion = fechaAutorizacion;
    }

    /**
     * @return the contabilizado
     */
    public int getContabilizado() {
        return contabilizado;
    }

    /**
     * @param contabilizado the contabilizado to set
     */
    public void setContabilizado(int contabilizado) {
        this.contabilizado = contabilizado;
    }

    /**
     * @return the anulado
     */
    public int getAnulado() {
        return anulado;
    }

    /**
     * @param anulado the anulado to set
     */
    public void setAnulado(int anulado) {
        this.anulado = anulado;
    }

    /**
     * @return the xml
     */
    public String getXml() {
        return xml;
    }

    /**
     * @param xml the xml to set
     */
    public void setXml(String xml) {
        this.xml = xml;
    }

    /**
     *
     * @return
     */
    public String getNombreDocumento() {
        return nombreDocumento;
    }

    /**
     *
     * @param nombreDocumento
     */
    public void setNombreDocumento(String nombreDocumento) {
        this.nombreDocumento = nombreDocumento;
    }

    /**
     *
     * @return
     */
    public String getDocumentXML() {
        return documentXML;
    }

    /**
     *
     * @param documentXML
     */
    public void setDocumentXML(String documentXML) {
        this.documentXML = documentXML;
    }

    /**
     * @return the pathXml
     */
    public String getPathXml() {
        return pathXml;
    }

    /**
     * @param pathXml the pathXml to set
     */
    public void setPathXml(String pathXml) {
        this.pathXml = pathXml;
    }

    /**
     * @return the pathPdf
     */
    public String getPathPdf() {
        return pathPdf;
    }

    /**
     * @param pathPdf the pathPdf to set
     */
    public void setPathPdf(String pathPdf) {
        this.pathPdf = pathPdf;
    }

    /**
     * @return the escenario
     */
    public int getEscenario() {
        return escenario;
    }

    /**
     * @param escenario the escenario to set
     */
    public void setEscenario(int escenario) {
        this.escenario = escenario;
    }

    /**
     * @return the estado
     */
    public String getEstado() {
        return estado;
    }

    /**
     * @param estado the estado to set
     */
    public void setEstado(String estado) {
        this.estado = estado;
    }

    /**
     * @return the log
     */
    public String getLog() {
        return log;
    }

    /**
     * @param log the log to set
     */
    public void setLog(String log) {
        this.log = log;
    }

    /**
     * @return the pdf
     */
    public int getPdf() {
        return pdf;
    }

    /**
     * @param pdf the pdf to set
     */
    public void setPdf(int pdf) {
        this.pdf = pdf;
    }

    /**
     * @return the email
     */
    public int getEmail() {
        return email;
    }

    /**
     * @param email the email to set
     */
    public void setEmail(int email) {
        this.email = email;
    }

    /**
     *
     * @return
     */
    public int getNotificacion() {
        return notificacion;
    }

    /**
     *
     * @param notificacion
     */
    public void setNotificacion(int notificacion) {
        this.notificacion = notificacion;
    }

    /**
     * @return the ultimo
     */
    public int getUltimo() {
        return ultimo;
    }

    /**
     * @param ultimo the ultimo to set
     */
    public void setUltimo(int ultimo) {
        this.ultimo = ultimo;
    }

    /**
     * @return the recepcionado
     */
    public int getRecepcionado() {
        return recepcionado;
    }

    /**
     * @param recepcionado the recepcionado to set
     */
    public void setRecepcionado(int recepcionado) {
        this.recepcionado = recepcionado;
    }

    /**
     * @return the autorizado
     */
    public int getAutorizado() {
        return autorizado;
    }

    /**
     * @param autorizado the autorizado to set
     */
    public void setAutorizado(int autorizado) {
        this.autorizado = autorizado;
    }

    /**
     * @return the usuario
     */
    public String getUsuario() {
        return usuario;
    }

    /**
     * @param usuario the usuario to set
     */
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    /**
     * @return the terminal
     */
    public String getTerminal() {
        return terminal;
    }

    /**
     * @param terminal the terminal to set
     */
    public void setTerminal(String terminal) {
        this.terminal = terminal;
    }

    /**
     * @return the emailDestino
     */
    public String getEmailDestino() {
        return emailDestino;
    }

    /**
     * @param emailDestino the emailDestino to set
     */
    public void setEmailDestino(String emailDestino) {
        this.emailDestino = emailDestino;
    }

    /**
     * @return the fechaRegistro
     */
    public Date getFechaRegistro() {
        return fechaRegistro;
    }

    /**
     * @param fechaRegistro the fechaRegistro to set
     */
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }

    public String getMensaje() {
        return mensaje;
    }

    public int getOffline() {
        return offline;
    }

    public void setOffline(int offline) {
        this.offline = offline;
    }

    public String getInterlocutor() {
        return interlocutor;
    }

    public void setInterlocutor(String interlocutor) {
        this.interlocutor = interlocutor;
    }

    public String getRazonSocial() {
        return razonSocial;
    }

    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    public String getDocSustento() {
        return docSustento;
    }

    public void setDocSustento(String docSustento) {
        this.docSustento = docSustento;
    }

    public String getRucCliente() {
        return rucCliente;
    }

    public void setRucCliente(String rucCliente) {
        this.rucCliente = rucCliente;
    }

}
