package com.csti.ce.monitor.domain;
// Generated 13/04/2014 12:19:59 PM by Hibernate Tools 3.6.0



/**
 * Parametro generated by hbm2java
 */
public class Parametro  implements java.io.Serializable {


     private int idParametro;
     private String programa;
     private String campo;
     private Integer posicion;
     private String opcion;
     private String parametroLow;
     private String parametroHigh;

    public Parametro() {
    }

	
    public Parametro(int idParametro) {
        this.idParametro = idParametro;
    }
   
    public int getIdParametro() {
        return this.idParametro;
    }
    
    public void setIdParametro(int idParametro) {
        this.idParametro = idParametro;
    }
    public String getPrograma() {
        return this.programa;
    }
    
    public void setPrograma(String programa) {
        this.programa = programa;
    }
    public String getCampo() {
        return this.campo;
    }
    
    public void setCampo(String campo) {
        this.campo = campo;
    }
    public Integer getPosicion() {
        return this.posicion;
    }
    
    public void setPosicion(Integer posicion) {
        this.posicion = posicion;
    }
    public String getOpcion() {
        return this.opcion;
    }
    
    public void setOpcion(String opcion) {
        this.opcion = opcion;
    }
    public String getParametroLow() {
        return this.parametroLow;
    }
    
    public void setParametroLow(String parametroLow) {
        this.parametroLow = parametroLow;
    }
    public String getParametroHigh() {
        return this.parametroHigh;
    }
    
    public void setParametroHigh(String parametroHigh) {
        this.parametroHigh = parametroHigh;
    }




}


